general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window.dimensions]
columns = 120
lines = 32

[cursor]
style = { shape = "Beam", blinking = "Always" }
